### ISSUE TITLE
Ingest METAR data directly into Couchbase

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxIngest#22]
Using the MADIS netCDF files maintained by DSG, write new ingest code (derived from the transfer scripts) that utilizes the template paradigm to read, process, and load the necessary variables into the Couchbase cluster

**Comment by randytpierce** [comment]
Creating a new directory in a branch named after this issue - netcdf_to_cb, and building new builders etc in that directory.

**Comment by randytpierce** [comment]
I have created and pushed a feature branch named VXingest-issue-22 to the repo and inside it I have created a netcdf_to_cb directory and begun coding the NetcdfBuilder class.

**Comment by JeffHamiltonNOAA** [comment]
I'm currently building two templates that will govern the ingest of METAR netCDF data and HRRR surface model data to match the METAR data. One template is currently inside the CB DB as "MD:V01:METAR:obs:ingest:netcdf". The next one will be "MD:V01:METAR:HRRR_OPS:ingest:grib2" once it is inside the database

**Comment by JeffHamiltonNOAA** [comment]
I also am compiling pseudo code that governs all of the data transformations necessary to get raw METAR data into a useable format inside the database. An example is transforming sky cover into ceiling. This will be necessary for both METAR data and model data (U and V components into wind speed and wind direction). I'll share this document once completed

**Comment by randytpierce** [comment]
I have the netcdfObsBuilder fairly complete, continuing with vscode learning curve, and unit test framework. Have one unit test working - mostly. Feels like about 80% complete at the moment.

**Comment by randytpierce** [comment]
I have created a directory on adb-cb1 in the /data directory
/data/netcdf_to_cb/load_specs to hold load_spec files
and /data/netcdf_to_cb/output to hold output files
for testing the latest code. I also merged the VXingest-issue-22 branch into development, and development into main so that we have a good baseline for the milestone 1.5.
I am closing this issue because the code should be complete for this development effort. Further code changes will be bug fixes or enhancements.
