### ISSUE TITLE
Design a better monitoring system

### ISSUE THREAD

**Issue by bonnystrong** [NOAA-GSL/VxIngest#36]
Need to reduce the number of warnings and errors to be more effective.  Also need to be able to turn alarms off if, for example, jet is down for routine maintenance.  Need to be able to acknowledge alarm and it is turned off until it stops and then restarts.  Also manage who receives alerts easily.

Consider tools such as nagios or prometheus.

**Comment by randytpierce** [comment]
one technique for this could involve querying the database to find out how recently specific data has been ingested. For example in order to get a ceiling document you need both a model and an observation at the necessary forecast time so a query like...
```
SELECT fcstValidISO, fcstValidEpoch, model
FROM mdata
WHERE 
    type="DD"
    AND version="V01"
    AND subset="METAR"
    AND model="HRRR_OPS"
    AND docType="CTC"
    AND subDocType="CEILING"
    order by id desc
Limit 1;
```
would return the most recent fcstValidTime for a ceiling document for the model "HRRR_OPS" which by inference tells us that the corresponding observation and model data is up to date at that time. This kind of query could be built into a monitoring client. It could be made specific to a region as well. I'll make a script and put it into the scripts directory to capture this technique.

**Comment by randytpierce** [comment]
The above utility is finished and in the scripts directory. example....
~/VXingest/scripts/VXingest_utilities/get_latest_fcstValidEpoch_CTC.sh -c ~/adb-cb1-credentials -s "METAR" -m "HRRR_OPS"
1650585600

**Comment by randytpierce** [comment]
I added another utility that checks for a given model and subset to see if there exists CTC CEILING data within a given "hours" ago.
example...
./scripts/VXingest_utilities/check_recent_fcstValidEpoch_CTC.sh -c ~/adb-cb1-credentials -s METAR -m HRRR_OPS -h 1
echo $?
1
./scripts/VXingest_utilities/check_recent_fcstValidEpoch_CTC.sh -c ~/adb-cb1-credentials -s METAR -m HRRR_OPS -h 2
1650898800
echo $?
0
